<section id="page">
			<header class="page-header">
				<div class="container">
					<div class="row">
						<div class="col-sm-6">
							<h1>About us</h1>
						</div>
						<div class="col-sm-6 hidden-xs">
							<ul id="navTrail">
								<li><a href="../">Home</a></li>
								<li id="navTrailLast">About us</li>
							</ul>
						</div>
					</div>
				</div>
			</header>
			<section id="content" class="mt30 pb30">
				<div class="container">
					<div class="row">
						
							<!-- intro -->



							<div class="row mt30 mb30">
								<div class="col-sm-12">
									<h2>Optimum Management Built on Integrity</h2>
									<!-- accordion -->

									<div class="panel-group" id="accordion">
										<div class="panel panel-default">
											<div class="panel-heading">
												<h4 class="panel-title" style="font-size:22px;">
													<a data-parent="#accordion" href="#collapseOne" style="color:white;">
														<i class="icon-location"></i>Vision
													</a>
												</h4>
											</div>
											<div id="collapseOne" class="panel-collapse in" >
												<div class="panel-body">
												Our vision is to be the premier sports and entertainment agency to professional athletes, entertainers, and executives.  
												</div>
											</div>
										</div>

										<div class="panel panel-default">
											<div class="panel-heading">
												<h4 class="panel-title" style="font-size:22px;">
													<a data-parent="#accordion" href="#collapseTwo" style="color:white;">
														<i class="icon-edit"></i>Mission
													</a>
												</h4>
											</div>
											<div id="collapseTwo" class="panel-collapse in">
												<div class="panel-body">
													OMBI Group, LLC’s mission is to serve our clients on a global basis.  We want to build well-rounded clients, who can meet their career goals and objectives. We personally commit to assisting our clients with integrity in helping them build a legacy that goes beyond their careers, while providing a first-class experience.   
												</div>
											</div>
										</div>

							

									</div>
								</div>


								
			

							</div>

							<div class="row team mt30 mb30">
								<div class="col-md-12 ">
									<h2>Who We Are</h2>
									<p>OMBI Group, LLC is the premier sports and entertainment agency that specializes in the representation of sports and entertainment professionals and executives.  We provide our clients with a "one-stop-shop" in contract negotiation, brand management, corporate visibility, community engagement, business consultation, and event implementation and management.  Founded in 2003 as a non-profit consulting agency, OMBI Group Founder and CEO, Kimberly K. Haynes decided to expand her company to one that would service the business and career needs of all of its clients.</p>
									<p>Our team has more than 15 years of experience in the sports and entertainment industries. We have a highly respected team of entertainment and sports professionals who believe in educating and empowering our clients to taking their careers to the next level.</p>
								</div>
							</div>
							<!-- intro -->
				
							<hr />
							<!-- team -->
							<div class="row team mt30 mb30">

								<div class="col-sm-12 likeboxcontent">
									<h2>Meet our team </h2>
									<h3>Kimberly K. Haynes, Esq. - Founder and CEO</h3>
									<p>Ms. Haynes serves as Founder and CEO where 

she has more than fifteen years of experience in the sports and entertainment industries.  Haynes’ 

emphasis is on making sure that each client feels as if he/she is the agencies only client.  She and her 

team are dedicated individuals who truly provide optimum management to their clients.</p>


<h3>Briana Houston - Executive Assistant/Talent Scout</h3> <p>Ms. Houston serves as Executive 

Assistant/Talent Scout where she is responsible for assisting the Company’s CEO with day-to-

day needs and overseeing many of the Company’s event logistics.  She helps with client services, 

marketing, recruiting, and intern supervision.  She is responsible for researching, marketing, 

recruiting and supervising the Company’s current and prospective talent. Additionally, she helps 

the Company determine how best to use the procured talent in consumer marketing and business-

to-business programs. Houston also assists clients with their day-to-day needs by working closely 

with them to ensure all of their off-field requests are met.</p>





								</div>


			<section id="content" class="mt30 pb30">
				<div class="container">
					<div class="bs-docs-section">
<div class="bs-example bs-example-tabs mb30">
							<ul id="myTab" class="nav nav-tabs" style="margin-left: -15px;">
								<li class="active"><a href="#home-tab" data-toggle="tab">Entertainment</a></li>
								<li ><a href="#profile" data-toggle="tab">Sports</a></li>

							</ul>
							<div id="myTabContent" class="tab-content">
								<div class="tab-pane fade active in" id="home-tab">
						<style>.leftAlign {text-align: left;}</style>			
<div class="col-sm-6">
									<article>
									
										<div class="boxContent text-center">
											<h3 class="leftAlign">Lauren R. McAlpin, Esq. – Vice President of Music</h3>
											<p class="leftAlign">Ms. McAlpin serves as 

Vice President of Music where she is responsible for expanding, identifying, and developing 

business opportunities within OMBI Group’s music division. In addition, she is charged with 

procuring new projects outside of the current OMBI Group roster. </p>
										</div>
									</article>
								</div>


								<div class="col-sm-6">
									<article>

										<div class="boxContent text-center">
											<h3 class="leftAlign">Nikki Tucker - Vice President of Entertainment</h3>
											<p class="leftAlign">Ms. Tucker serves as Vice President of 

Entertainment where she is responsible for overseeing artist management and talent acquisition 

within OMBI Group’s Entertainment Division.  She is also responsible for expanding, 

identifying, and developing business opportunities and procuring new projects outside of the 

current OMBI Group roster.  In addition, she is responsible for the Company’s philanthropic 

efforts, events and property representation.</p>
										</div>
									</article>
								</div>
								




								</div>
								<div class="tab-pane" id="profile">
									

<div class="col-sm-6">
									<article>
						
										<div class="boxContent">
											<h3 class="leftAlign">Veronica Higgs Cope, Esq. - Vice President of Sports Operations</h3>
											<p class="leftAlign">Ms. Cope is a certified NFL sports agent who serves as Vice President of Sports Operations, where she is responsible for overseeing athlete contract negotiations, endorsements, licensing, marketing, and merchandising opportunities. She also is responsible 

for formulating policies and strategic plans for the department’s future growth, including 

intellectual property, talent procurement, and managing the Company’s day-to-day sports 

division operations. </p>
										</div>
									</article>
								</div>


								<div class="col-sm-6">
									<article>
						
										<div class="boxContent  text-center">
											<h3 class="leftAlign">Lauren R. McAlpin, Esq. - Certified NFL Sports Agent</h3>
											<p class="leftAlign">Ms. McAlpin serves as a 

certified NFL sports agent where she is responsible for managing a diverse roster of professional 

athletes in all “on the field” endeavors (including, but not limited to: overseeing football contract 

negotiation, marketing, and endorsements; player representation; and interfacing with General 

Managers and teams front offices). She helps forge and develop new client relationships to build 

OMBI Group’s visibility, impact, and client base. </p>
										</div>
									</article>
								</div>
								




								</div>

							</div>
						</div>
					</div>
				</section>			


							</div>

					</div>
					<!-- end row -->
				</div>
				<!-- end container -->
			</section>
			<!-- content -->



	