	<section id="page">
			<header class="page-header">
				<div class="container">
					<div class="row">
						<div class="col-sm-6">
							<h1>Stay in touch with us</h1>
						</div>
						<div class="col-sm-6 hidden-xs">
							<ul id="navTrail">
								<li><a href="../">Home</a></li>
								<li id="navTrailLast">Contact Us</li>
							</ul>
						</div>
					</div>
				</div>
			</header>
			<section id="content">
				<div id="mapWrapperSatellite" class="mb40"></div>
				<div class="container">

					<div class="row pb40">

						<div class="col-sm-4">
							<h4>Address:</h4>
							<address>
								<p>
									<i class="icon-location"></i>&nbsp;2020 Howell Mill Road <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Suite C-219<br>
									&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Atlanta, Georgia 30318<br>
									<i class="icon-phone"></i>&nbsp;404.822.3231 <br>
									<i class="icon-mail-alt"></i>&nbsp;<a href="mailto: info@ombigroup.com">info@ombigroup.com</a>
								</p>
							</address>
						</div>
					
					</div>
				</div>
				
			</section>
		</section>
		<!-- content -->