<!-- footer -->
<footer id="footerWrapper" class="footer2">
	<section id="mainFooter">
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-sm-6">
					<div class="footerWidget">
						<img src="<?php echo $sub; ?>images/side-logo.png" title="OMBI GROUP - Optimum Management Built on Integrity" id="footerLogo">
						<p><a href="/aboutus" title="About Ombi Group">OMBI Group</a>, LLC was established in January 2003 with our home office located in Atlanta, Georgia. We represent clients in the National Football League (NFL), Major League Baseball (MLB), National Basketball Association (NBA), Women's National Basketball Association (WNBA), and USA Track and Field.</p>
					</div>
				</div>


				<!--<div class="col-md-3 col-sm-6">
					<div class="footerWidget">

						<h3>Latest Media</h3>
						<ul class="list-unstyled worksList">
							<li><a href="../gallery" class="tips" title="" data-original-title="Little Neko work"><img src="<?php echo $sub; ?>images/theme-pics/works1.jpg" alt="works"></a></li>
							<li><a href="../gallery" class="tips" title="" data-original-title="Little Neko work"><img src="<?php echo $sub; ?>images/theme-pics/works2.jpg" alt="works"></a></li>
							<li><a href="../gallery" class="tips" title="" data-original-title="Little Neko work"><img src="<?php echo $sub; ?>images/theme-pics/works3.jpg" alt="works"></a></li>
							<li><a href="../gallery" class="tips" title="" data-original-title="Little Neko work"><img src="<?php echo $sub; ?>images/theme-pics/works4.jpg" alt="works"></a></li>
							<li><a href="../gallery" class="tips" title="" data-original-title="Little Neko work"><img src="<?php echo $sub; ?>images/theme-pics/works5.jpg" alt="works"></a></li>
							<li><a href="../gallery" class="tips" title="" data-original-title="Little Neko work"><img src="<?php echo $sub; ?>images/theme-pics/works6.jpg" alt="works"></a></li>

						</ul>
					</div>
				</div> -->



				<div class="col-md-3 col-sm-6">
					<div class="footerWidget">

						<h3>Latest news</h3>
						<ul class="list-unstyled iconList borderList">
							<li><a href="../news">Harland Boys and Girls Club</a></li>
							<li><a href="../news">NFL Football Camp</a></li>
							<li><a href="../news">Fall 2009-Volume 1 Issue 4</a></li>
						</ul>
					</div>
				</div>
				<div class="col-md-3 col-sm-6">
					<div class="footerWidget">

						<h3>OMBI GROUP</h3>
						<address>
							<p>
							
								<i class="icon-mail-alt"></i>&nbsp;<a href="mailto:info@ombigroup.com">info@ombigroup.com</a>
							</p>
						</address>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section id="footerRights">
		<div class="container">
			<div class="row">

				<div class="col-md-12">
					<ul class="socialNetwork">
						<li><a href="https://twitter.com/ombi_group" class="tips" title="" data-original-title="follow us on Facebook"><i class="icon-facebook-1 iconRounded"></i></a></li>
						<li><a href="https://www.facebook.com/kimberly.haynes.739" class="tips" title="" data-original-title="follow us on Twitter"><i class="icon-twitter-bird iconRounded"></i></a></li>
						<li><a href="https://instagram.com/ombigroup04" class="tips" title="" data-original-title="follow us on Instagram"><i class="icon-instagramm iconRounded"></i></a></li>

					</ul>     
				</div>


				<div class="col-md-12">
					<p>Copyright © 2015 <a href="http://www.ombigroup.com" target="blank">OMBI Group</a> / All rights reserved.</p>
				</div>

			</div>
		</div>
	</section>
</footer>
<!-- End footer -->
</div>
<!-- global wrapper -->
<!-- End Document 
	================================================== -->
	<script type="text/javascript" src="<?php echo $sub; ?>js-plugin/respond/respond.min.js"></script>
	<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
	<script type="text/javascript" src="<?php echo $sub; ?>js-plugin/jquery-ui/jquery-ui-1.8.23.custom.min.js"></script>
	<!-- third party plugins  -->
	<script type="text/javascript" src="<?php echo $sub; ?>bootstrap/js/bootstrap.js"></script>
	<script type="text/javascript" src="<?php echo $sub; ?>js-plugin/easing/jquery.easing.1.3.js"></script>
	<!-- carousel -->
	<script type="text/javascript" src="<?php echo $sub; ?>js-plugin/owl.carousel/owl-carousel/owl.carousel.min.js"></script>
	<!-- pop up -->
	<script type="text/javascript" src="<?php echo $sub; ?>js-plugin/magnific-popup/jquery.magnific-popup.min.js"></script>
	<!-- Revolution slider -->
	<script type="text/javascript" src="<?php echo $sub; ?>js-plugin/revolution-slider/rs-plugin/js/jquery.themepunch.plugins.min.js"></script>
	<script type="text/javascript" src="<?php echo $sub; ?>js-plugin/revolution-slider/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
	<!-- isotope -->
	<script type="text/javascript" src="<?php echo $sub; ?>js-plugin/isotope/jquery.isotope.min.js"></script>
	<!-- form -->
	<script type="text/javascript" src="<?php echo $sub; ?>js-plugin/neko-contact-ajax-plugin/js/jquery.form.js"></script>
	<script type="text/javascript" src="<?php echo $sub; ?>js-plugin/neko-contact-ajax-plugin/js/jquery.validate.min.js"></script>
	<!-- parallax -->
	<script type="text/javascript" src="<?php echo $sub; ?>js-plugin/parallax/js/jquery.stellar.min.js"></script>
	<!-- appear -->
	<script type="text/javascript" src="<?php echo $sub; ?>js-plugin/appear/jquery.appear.js"></script>

	<!-- toucheeffect -->
	<script type="text/javascript" src="<?php echo $sub; ?>js-plugin/toucheeffect/toucheffects.js"></script>

	<!-- Custom  -->
	<script type="text/javascript" src="<?php echo $sub; ?>js/custom.js"></script>