<head>
<!-- Basic Page Needs
	================================================== -->
	<meta charset="utf-8">
	<title>OMBI Group</title>
	<meta name="description" content="OMBI Group<">
	<meta name="author" content="OMBI Group<">
<!-- Mobile Specific Metas
	================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<!-- CSS
	================================================== -->
	<!-- Bootstrap  -->
	<link type="text/css" rel="stylesheet" href="<?php echo $sub; ?>/bootstrap/css/bootstrap.min.css">
	<!-- web font  -->
	<link href='http://fonts.googleapis.com/css?family=Roboto:100,300,400' rel='stylesheet' type='text/css'>
	<!-- plugin css  -->
	<link rel="stylesheet" type="text/css" href="<?php echo $sub; ?>js-plugin/animation-framework/animate.css" />
	<!-- Pop up-->
	<link rel="stylesheet" type="text/css" href="<?php echo $sub; ?>js-plugin/magnific-popup/magnific-popup.css" />
	<!-- Revolution Slider -->
	<link rel="stylesheet" type="text/css" href="<?php echo $sub; ?>js-plugin/revolution-slider/rs-plugin/css/navstylechange.css" media="screen" />
	<link rel="stylesheet" type="text/css" href="<?php echo $sub; ?>js-plugin/revolution-slider/rs-plugin/css/settings-hideo.css" media="screen" />

	<!-- nekoAnim-->
	<link rel="stylesheet" type="text/css" href="<?php echo $sub; ?>js-plugin/appear/nekoAnim.css" />
	
	<!-- Owl carousel-->
	<link rel="stylesheet" href="<?php echo $sub; ?>js-plugin/owl.carousel/owl-carousel/owl.carousel.css">
	<link rel="stylesheet" href="<?php echo $sub; ?>js-plugin/owl.carousel/owl-carousel/owl.transitions.css">
	<link rel="stylesheet" href="<?php echo $sub; ?>js-plugin/owl.carousel/owl-carousel/owl.theme.css">
	<!-- icon fonts -->
	<link type="text/css" rel="stylesheet" href="<?php echo $sub; ?>font-icons/custom-icons/css/custom-icons.css">
	<!-- Custom css -->
	<link type="text/css" rel="stylesheet" href="<?php echo $sub; ?>css/layout.css">
	<link type="text/css" id="colors" rel="stylesheet" href="<?php echo $sub; ?>css/dark-orange.css">
	<link type="text/css" rel="stylesheet" href="<?php echo $sub; ?>css/custom.css">
	<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script> <![endif]-->
	<script src="<?php echo $sub; ?>js/modernizr-2.6.1.min.js"></script>
<!-- Favicons
	================================================== -->
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
<link rel="icon" href="/favicon.ico" type="image/x-icon">



</head>