		<section id="rsDemoWrapper">

			<div class="tp-banner-container">
				<div class="tp-banner" >
					<ul>	<!-- SLIDE  -->
						<li data-transition="fade" data-slotamount="7" data-masterspeed="1500" >
							<!-- MAIN IMAGE -->
							<img src="images/bck8.jpg"  alt="slidebg1"  data-bgfit="cover" data-bgposition="left bottom" data-bgrepeat="no-repeat">
							<!-- LAYERS -->
							<!-- LAYER NR. 1 -->
							<div class="tp-caption tp-resizeme"
							data-x="center" data-hoffset="0"
							data-y="150"
							data-speed="600"
							data-start="1400"
							data-endspeed="600"
							>
							<img src="images/logo100.png" alt="OMBI Logo" />

						</div>

						<!-- LAYER NR. 2 -->
						<div class="tp-caption large_bold_white customin customout tp-resizeme"
						data-x="center" data-hoffset="0"
						data-y="250"
						data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:5;scaleY:5;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
						data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
						data-speed="600"
						data-start="2400"
						data-easing="Power4.easeOut"
						data-endspeed="600"
						data-endeasing="Power0.easeIn"
						style="z-index: 3">Optimum Management Built on Integrity

					</div>

					<!-- LAYER NR. 3 -->
					<div class="tp-caption medium_light_white customin customout tp-resizeme"
					data-x="center" data-hoffset="0"
					data-y="bottom" data-voffset="-140"
					data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:5;scaleY:5;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
					data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
					data-speed="600"
					data-start="2700"
					data-easing="Power4.easeOut"
					data-endspeed="600"
					data-endeasing="Power0.easeIn"
					style="z-index: 4">A premier sports and entertainment agency for professional athletes, entertainers, and executives

			</li>

			<li data-transition="fade" data-slotamount="7" data-masterspeed="1500" >
				<!-- MAIN IMAGE -->
				<img src="images/bck4.jpg"  alt="slidebg1"  data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">
				<!-- LAYERS -->
				<!-- LAYER NR. 2 -->
				<div class="tp-caption largeblackbg skewfromleft tp-resizeme"
				data-x="20" data-hoffset="0"
				data-y="200"
				data-speed="600"
				data-start="1400"
				data-easing="Power4.easeOut"
				data-endspeed="600"
				data-endeasing="Power0.easeIn"
				style="z-index: 3">Over 15 years of experience

			</div>

			<!-- LAYER NR. 3 -->
			<div class="tp-caption medium_light_white skewfromleft tp-resizeme"
			data-x="20" data-hoffset="0"
			data-y="280"
			data-speed="600"
			data-start="1800"
			data-easing="Power4.easeOut"
			data-endspeed="600"
			data-endeasing="Power0.easeIn"
			style="z-index: 3"> Educating and empowering our clients

		</div>

		<!-- LAYER NR. 4 -->
		<div class="tp-caption medium_light_white skewfromleft tp-resizeme"
		data-x="20" data-hoffset="0"
		data-y="320"
		data-speed="600"
		data-start="2200"
		data-easing="Power4.easeOut"
		data-endspeed="600"
		data-endeasing="Power0.easeIn"
		style="z-index: 3"> and taking their careers to the next level

	</div>

</li>

<li data-transition="fade" data-slotamount="7" data-masterspeed="1500" >
	<!-- MAIN IMAGE -->
	<img src="images/bck6.jpg"  alt="slidebg3"  data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">
	<!-- LAYERS -->

	<!-- LAYER NR. 2 -->
	<div class="tp-caption largeblackbg skewfromleft tp-resizeme"
	data-x="20" data-hoffset="0"
	data-y="200"
	data-speed="600"
	data-start="1400"
	data-easing="Power4.easeOut"
	data-endspeed="600"
	data-endeasing="Power0.easeIn"
	style="z-index: 3">Highly respected team 

</div>

<!-- LAYER NR. 3 -->
<div class="tp-caption medium_light_white skewfromleft tp-resizeme"
data-x="20" data-hoffset="0"
data-y="280"
data-speed="600"
data-start="1800"
data-easing="Power4.easeOut"
data-endspeed="600"
data-endeasing="Power0.easeIn"
style="z-index: 3"><i class="icon-right-open-mini"></i>"One-stop-shop" in client management

</div>

<!-- LAYER NR. 4 -->
<div class="tp-caption medium_light_white skewfromleft tp-resizeme"
data-x="20" data-hoffset="0"
data-y="320"
data-speed="600"
data-start="2200"
data-easing="Power4.easeOut"
data-endspeed="600"
data-endeasing="Power0.easeIn"
style="z-index: 3"><i class="icon-right-open-mini"></i>Brand management & corporate visibility

</div>

<!-- LAYER NR. 4 -->
<div class="tp-caption medium_light_white skewfromleft tp-resizeme"
data-x="20" data-hoffset="0"
data-y="360"
data-speed="600"
data-start="2600"
data-easing="Power4.easeOut"
data-endspeed="600"
data-endeasing="Power0.easeIn"
style="z-index: 3"><i class="icon-right-open-mini"></i>Community engagement

</div>
</li>
</ul>
</div>
</div>

</section>
<!-- slider -->


<section id="content">
	<section class="largeQuote pb40 pt40">
		<div class="container">
			<div class="row">
				<div class="span12 text-center">
					<h1>We build well-rounded clients, <strong>who meet their career objectives!</strong><br/><small>Assisting our clients with integrity in helping them build a legacy</small></h1>

				</div>
			</div>
		</div>
	</section>
	<!-- services -->
	<section id="services">
		<div class="container pb30 pt15">

			<div class="row">
				<div class="col-md-3 col-sm-6">
					<article class="boxIcon" data-nekoanim="fadeInLeftBig" data-nekodelay="100">
						<a href="/aboutus/">
							<i class="icon-font iconBig iconRounded"></i>
							<h2>About Us</h2>
							<p>We have a highly respected team of entertainment and sports professionals.</p>
						</a>
					</article>
				</div>

				<div class="col-md-3 col-sm-6">
					<article class="boxIcon" data-nekoanim="fadeIn" data-nekodelay="200">
						<a href="/services/">
							<i class="icon-list iconBig iconRounded"></i>
							<h2>Services</h2>
							<p>Community engagement and personal development are our focus for our clients.</p>
						</a>
					</article>
				</div>

				<div class="col-md-3 col-sm-6">
					<article class="boxIcon" data-nekoanim="fadeIn" data-nekodelay="300">
						<a href="/news/">
							<i class="icon-align-justify iconBig iconRounded"></i>
							<h2>News</h2>
							<p>Check out our news, press releases and newsletters.</p>
						</a>
					</article>
				</div>

				<div class="col-md-3 col-sm-6">
					<article class="boxIcon" data-nekoanim="fadeInRightBig" data-nekodelay="400">
						<a href="/partners/">
							<i class="icon-th iconBig iconRounded"></i>
							<h2>Stategic Partners</h2>
							<p>We are very appreciative of the companies that have come on board to help us service our clients.</p>
						</a>
					</article>
				</div>
			</div>

			<div class="row">
				<div class="col-md-12 mb30">
					<hr class="lineLines">
				</div>
			</div>

		</div>
	</section>
	<!-- services -->
	<!-- works -->
	<section class="imgHover clearfix cs-style-3 mb40">
		<div class="container">
			<div class="row">
				<div class="span12 text-center mb40">
					<h1>Our work</h1>
					<h2 class="subTitle">Defines the individual...Refines the course... and Aligns Our client's vision with our Team's goals</h2>
				</div>
			</div>
		</div>

		<!-- works carousel -->

		<div class="owl-carousel nekoDataOwl imgHover neko-hover-1" data-neko_items="1"  data-neko_singleitem="true">
			<div class="item">
				<div class="container">
					<div class="row">

						<article class="col-md-6 mb30">
							<figure class="minimalBox">
								<img alt="" src="images/home/photo1.jpg" class="img-responsive">
								<figcaption>
									<h3>Willie Whitehead Foundation Youth Football Camp</h3>
									
									<a href="/gallery" class="btn projectLink" target="_blank">View More</a>
								</figcaption>
							</figure>	
						</article>

						<article class="col-md-6 mb30">
							<figure class="minimalBox">
								<img alt="" src="images/home/photo2.jpg" class="img-responsive">
								<figcaption>
									<h3>Photo</h3>
								
									<a href="/gallery" class="btn projectLink" target="_blank">View More</a>
								</figcaption>
							</figure>
						</article>
						
					</div>
					<div class="row">
						<article class="col-md-6 mb30">
							<figure class="minimalBox">
								<img alt="" src="images/home/JerrichoCotchery.jpg" class="img-responsive">

								<figcaption>
									<h3>Jerricho Cotchery</h3>
									
									<a href="/gallery" class="btn projectLink" target="_blank">View More</a>
								</figcaption>
							</figure>
						</article>

						<article class="col-md-6 mb30">
							<figure class="minimalBox">
								<img alt="" src="images/home/photo4.jpg" class="img-responsive">

								<figcaption>
								<h3>2014 Giving Gracefully Awards Honorees Tampa Bay Buccaneers wide receiver Louis Murphy and Carolina Panthers wide receiver Jerricho Cotchery</h3>
									<a href="/gallery" class="btn projectLink" target="_blank">View More</a>
								</figcaption>
							</figure>
						</article>
					</div>
				</div>
			</div>





			<div class="item">
				<div class="container">
					<div class="row">

						<article class="col-md-6 mb30">
							<figure class="minimalBox">
								<img alt="" src="images/home/photo5.jpg" class="img-responsive">


								<figcaption>
									<h3>Photo</h3>
									<a href="/gallery" class="btn projectLink" target="_blank">View More</a>
								</figcaption>
							</figure>
						</article>

						<article class="col-md-6 mb30">
							<figure class="minimalBox">
								<img alt="" src="images/home/photo6.jpg" class="img-responsive">


								<figcaption>
									<h3>Photo</h3>
									<a href="/gallery" class="btn projectLink" target="_blank">View More</a>
								</figcaption>
							</figure>
						</article>
					</div>
					<div class="row">
						<article class="col-md-6 mb30">
							<figure class="minimalBox">
								<img alt="" src="images/home/photo7.jpg" class="img-responsive">

								<figcaption>
									<h3>Photo</h3>
									<a href="/gallery" class="btn projectLink" target="_blank">View More</a>
								</figcaption>
							</figure>
						</article>

						<article class="col-md-6 mb30">
							<figure class="minimalBox">
								<img alt="" src="images/home/photo8.jpg" class="img-responsive">

								<figcaption>
									<h3>Photo</h3>
									<a href="/gallery" class="btn projectLink" target="_blank">View More</a>
								</figcaption>
							</figure>
						</article>

					</div>
				</div>
			</div>

			<div class="item">
				<div class="container">
					<div class="row">

						<article class="col-md-6 mb30">
							<figure class="minimalBox">
								<img alt="" src="images/home/photo9.jpg" class="img-responsive">


								<figcaption>
									<h3>Photo</h3>
									<a href="/gallery" class="btn projectLink" target="_blank">View More</a>
								</figcaption>
							</figure>
						</article>

						<article class="col-md-6 mb30">
							<figure class="minimalBox">
								<img alt="" src="images/home/photo10.jpg" class="img-responsive">


								<figcaption>
									<h3>Photo</h3>
									<a href="/gallery" class="btn projectLink" target="_blank">View More</a>
								</figcaption>
							</figure>
						</article>
					</div>
					<div class="row">
						<article class="col-md-6 mb30">
							<figure class="minimalBox">
								<img alt="" src="images/home/photo11.jpg" class="img-responsive">

								<figcaption>
									<h3>Photo</h3>
									<a href="/gallery" class="btn projectLink" target="_blank">View More</a>
								</figcaption>
							</figure>
						</article>

			

					</div>
				</div>
			</div>
		</div>
		<!-- works carousel -->

	</section>
	<!-- works -->



	<!-- team 

	<section id="team5" class="pt40 pb40">

		<div class="container">
			<div class="row"> 

				<div class="col-md-12 mb30 text-center">
					<h1>Meet our team</h1>
					<p class="subTitle">
						The Duchess took her choice, and was gone in a moment. 'Let's go on with the game,'<br/> the Queen said to Alice; and Alice was too much frightened to say a word, but slowly followed her back to the croquet-ground.
					</p>


				</div>
				<section class="col-md-12">

					<div class="row mb15">
						<div class="col-sm-12" data-nekoanim="fadeIn" data-nekodelay="200">
							<article>
								<div><img src="images/team/team-corporate-1.jpg" alt="" class="img-responsive imgBorder"></div>
								<div class="boxContent text-center">
									<h3>Kim Haynes</h3>
									<p>CEO</p>
								</div>
							</article>
						</div>
					</div>

					<div class="row mb15">
						<div class="col-sm-3" data-nekoanim="fadeIn" data-nekodelay="200">
							<article>
								<div class="boxContent text-center">
									<h3>Janice Rand</h3>
									<p>Executive Director</p>
								</div>
							</article>
						</div>
						<div class="col-sm-3" data-nekoanim="fadeIn" data-nekodelay="300">
							<article>
								<div class="boxContent text-center">
									<h3>Rick Deckard</h3>
									<p>Salesman</p>
								</div>
							</article>
						</div>
						<div class="col-sm-3" data-nekoanim="fadeIn" data-nekodelay="400">
							<article>
								<div class="boxContent text-center">
									<h3>Christine Chapel</h3>
									<p>Graphic designer</p>
								</div>
							</article>
						</div>
						<div class="col-sm-3" data-nekoanim="fadeIn" data-nekodelay="400">
							<article>
								<div class="boxContent text-center">
									<h3>Christine Chapel</h3>
									<p>Graphic designer</p>
								</div>
							</article>
						</div>
					</div>
				</section>


			</div>
		</div>

	</section>
-->
	<!-- team -->


</section>
<!-- content -->

<!-- call to action -->

<section class="color2 pb40 pt40">  
	<div class="ctaBox ctaBoxFullwidth">
		<div class="container">
			<div class="row">
				<div class="col-md-8">
					<h1>
						<strong>Keep up to date with all our latest news and events</strong><br />See what's coming up next... 
					</h1>
				</div>
				<div class="col-md-4">
					<a class="btn btn-lg btn-border" title="Keep up to date with all our latest news and events" href="/calendar" >
						<i class="icon-down-open-big"></i> Calendar
					</a>
				</div>
			</div>
		</div>
	</div>
</section>
