		<header class="navbar-fixed-top">
			<!-- pre header -->
			<div id="preHeader" class="hidden-xs">
				<div class="container">
					<div class="row">
						<div class="col-xs-6">
						<!-- 	<ul class="quickMenu">

									<li><a href="<?php echo $sub; ?>" >Home</a></li>
									<li><a href="<?php echo $sub; ?>/aboutus" >About Us</a></li>
									<li><a href="<?php echo $sub; ?>/services"  >Services</a></li>
									<li><a href="<?php echo $sub; ?>/news" >News</a></li>
									<li><a href="<?php echo $sub; ?>/calendar"  >Calendar</a></li>
									<li><a href="<?php echo $sub; ?>/gallery"  >Media Gallery</a></li>
									<li><a href="<?php echo $sub; ?>/partners"  >Stategic Partners</a></li>
									<li><a href="<?php echo $sub; ?>/contact" >Contact Us</a></li>

							</ul>-->
						</div>
						<div class="col-xs-6">
							<div id="contactBloc" class="clearfix">
								<!-- social icons -->
								<ul class="socialNetwork">
									<li><a href="https://twitter.com/ombi_group" class="tips" title="follow me on Facebook"> <i class="icon-facebook-1"></i></a></li>
									<li><a href="https://www.facebook.com/kimberly.haynes.739" class="tips" title="follow me on Twitter"> <i class="icon-twitter-bird"></i> </a> </li>
									<li><a href="https://instagram.com/ombigroup04" class="tips" title="follow me on Instagram"> <i class="icon-instagram"></i> </a> </li>
									<!-- social icons -->
								</ul>
								<!-- phone -->
								<span class="contactPhone"><i class="icon-mobile"></i>404.822.3231</span>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- pre header -->			
			<!-- header -->
			<div id="mainHeader" role="banner">
				<div class="container">
					<nav class="navbar navbar-default scrollMenu" role="navigation">
						<div class="navbar-header">
							<!-- responsive navigation -->
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
							<!-- Logo -->
							<a class="navbar-brand" href="./"><img src="<?php echo $sub; ?>images/main-logo.png" title="OMBI GROUP - Optimum Management Built on Integrity" alt="OMBI GROUP - Optimum Management Built on Integrity"/></a>
						</div>
						<div class="collapse navbar-collapse" id="mainMenu">
							<!-- Main navigation -->
							<ul class="nav navbar-nav pull-right">

								<li class="primary">
									<a href="<?php echo $sub; ?>" class="firstLevel active" >Home</a>
								</li>

								<li class="sep"></li>

								<li class="primary"> 
									<a href="<?php echo $sub; ?>/aboutus" class="firstLevel " >About Us</a>
								</li>

								<li class="sep"></li>

								<li class="primary"> 
									<a href="<?php echo $sub; ?>/services" class="firstLevel " >Services</a>
								</li>
								
								<li class="sep"></li>

								<li class="primary"> 
									<a href="<?php echo $sub; ?>/news" class="firstLevel " >News</a>
								</li>								

								<li class="sep"></li>

								<li class="primary"> 
									<a href="<?php echo $sub; ?>/calendar" class="firstLevel " >Calendar</a>
								</li>								

								<li class="sep"></li>
<!--
								<li class="primary"> 
									<a href="<?php echo $sub; ?>/gallery" class="firstLevel " >Media Gallery</a>
								</li>								

								<li class="sep"></li>
-->
								<li class="primary"> 
									<a href="<?php echo $sub; ?>/partners" class="firstLevel " >Stategic Partners</a>
								</li>
							
								<li class="sep"></li>

								<li id="lastMenu" class="last"><a href="<?php echo $sub; ?>/contact" class="firstLevel last">Contact Us</a></li>
							</ul>
							<!-- End main navigation -->
						</div>
					</nav>
				</div>
			</div>
		</header>

