<section id="page">
			<header class="page-header">
				<div class="container">
					<div class="row">
						<div class="col-sm-6">
							<h1>News</h1>
						</div>
						<div class="col-sm-6 hidden-xs">
							<ul id="navTrail">
								<li><a href="../">Home</a></li>
								<li id="navTrailLast">News</li>
							</ul>
						</div>
					</div>
				</div>
			</header>


		<section class="pb30 mt40">
					<div class="container">
						<div class="row">
						<!--	<div class="col-md-4">
								<article class="iconBlocHeading">
									<i class="icon-list-alt iconRounded"></i>
									<h2>In the News</h2>

									<p ><a href="inthenews/OTMagazine_Article.pdf" class="icon-download">OT Magazine Article - Spring 2006</a></p>
									
								</article>
							</div> -->
							<div class="col-md-4">
								<article class="iconBlocHeading">
									<i class="icon-doc-text-inv iconRounded"></i> 
									<h2>Newsletters</h2>
									<p ><a href="newsletters/Newsletter1-4.pdf" class="icon-download">Fall 2009-Volume 1 Issue 4 Featuring Philadelphia 76ers Lou Williams and Janice Faulkner- Undeniable Force</a></p>
									<p ><a href="newsletters/Newsletter1-3.pdf" class="icon-download">Spring 2008-Volume 1 Issue 3 Featuring New Orleans Saints' Willie Whitehead's Millionaire Tour</a></p>
									<p ><a href="newsletters/Newsletter1-1.pdf" class="icon-download">Summer 2008-Volume 1 Issue 1 Featuring Seattle Seahawks' Jimmy Williams' Summer Activity</a></p>

				
								</article>
							</div>
							<div class="col-md-4">
								<article class="iconBlocHeading">
									<i class="icon-megaphone iconRounded"></i> 
									<h2>Press Releases</h2>
									<p ><a href="pressreleases/PressRelease4-16-09.pdf" class="icon-download">NFL Football Camp</a></p>									
									<p ><a href="pressreleases/PressRelease10-16-12.pdf"  class="icon-download">Harland Boys and Girls Club</a></p>
								</article>
							</div>
						</div>
					

					

					</div>
				</section>


</section>