		<section id="page">
			<header class="page-header">
				<div class="container">
					<div class="row">
						<div class="col-sm-6">
							<h1>Our services</h1>
						</div>
						<div class="col-sm-6 hidden-xs">
							<ul id="navTrail">
								<li><a href="../">Home</a></li>
								<li id="navTrailLast">Services</li>
							</ul>
						</div>
					</div>
				</div>
			</header>


				<section class="largeQuote pb40 pt40">
					<div class="container">
						<div class="row">
							<div class="span12 text-center">
								<h1>What We Do<br><small>OMBI Group, LLC is a leader / pioneer in talent representation, nonprofit development and management, sports marketing, and client branding.  We bring brands to our clients and are unique in that we provide them with one-on-one consultation to help create long-term career and post career strategic planning.  Community engagement and personal development are two aspects of our clients’ lives that we believe are vitally important to their longevity.</small></h1>
							</div>
						</div>
					</div>
				</section>

				
				<section class="pt40 pb40 color1">
					<div class="container">
						<div class="row">
							

							<div class="col-md-4 mk-130p">
								<h2>Entertainment</h2>
							
<p >   Client Management</p>
<p >   Client Development</p>
<p >   Client Bookings</p>
<p >   Career Development</p>
<p >   Business Management</p>
<p >   Publicity</p>
<p >   Sponsorship Activation and Development</p>
<p >   Brand Management</p>
<p >   Nonprofit Formation and Management</p>
							

							</div>
							<div class="col-md-4">
								<img src="../images/white316logo.png" alt="OMBI Group" class="img-responsive" id="logo316" style="margin:0 auto;"/>
							</div>

							<div class="col-md-4 mk-130p">
								<h2>Sports</h2>

<p >   Contract negotiations</p>
<p >   Marketing and Endorsements</p>
<p >   Media Relations</p>
<p >   Post Career Counseling and Transition</p>
<p >   Community Involvement</p>
<p >   Draft Preparation</p>
<p >   Relocation Support</p>
<p >   Psychological Evaluations and Support</p>
<p >   Nonprofit Formation and Management</p>

							</div>
						</div>
					</div>
				</section>

		</section>